### ISSUE TITLE
Make All Failed 

### ISSUE THREAD

**Issue by JSybrandt** [openbigdatagroup/plda#17]
`In file included from model.h:23:0,
                 from model.cc:15:
model.cc: In constructor ‘learning_lda::LDAModel::LDAModel(std::istream&, std::map<std::__cxx11::basic_string<char>, int>*)’:
common.h:39:30: error: no match for ‘operator<<’ (operand types are ‘std::basic_ostream<char>’ and ‘std::basic_istream<char>’)
     std::cerr << "CHECK failed "                                        \
     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               << __FILE__ << ":" << __LINE__ << "\n"                    \
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
               << #a << " = " << (a) << "\n";                            \
               ~~~~~~~~~~~~~~~^~~~~~
`

I am using mpich 3.2 and g++ (GCC) 6.1.0

**Comment by JSybrandt** [comment]
Attempted install on different system

    Makefile:28: recipe for target 'mpi_lda' failed
    make: *** [mpi_lda] Error 127

g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0
mpich version (3.2-6build1)

**Comment by steeeeevo1** [comment]
Were you able to fix this issue?

**Comment by JSybrandt** [comment]
No actually. I ended up getting a binary from a friend of mine who figured something out almost a year ago and has been copying the same binary ever since. Of course he doesn't remember.

**Comment by steeeeevo1** [comment]
FWIW, I was able to resolve this issue using g++ 5.3.0 and openmpi 1.6.5 on Red Hat 4.4.7.

**Comment by torchmike** [comment]
Hey! I was having trouble getting this to compile on ubuntu 17.04 but on 16.04 it compiled fine. if you delete lines 37-39 from common.h ( the stderr print ) it compiles fine.

**Comment by ghuls** [comment]
Telling g++ to expect c++03 code worked for me:
```diff
❯  git diff
diff --git a/Makefile b/Makefile
index 7191995..1b56196 100644
--- a/Makefile
+++ b/Makefile
@@ -1,7 +1,7 @@
 CC=g++
 MPICC=mpicxx
 
-CFLAGS=-O3 -Wall -Wno-sign-compare
+CFLAGS=-O3 -std=c++03 -Wall -Wno-sign-compare
 OBJ_PATH = ./obj
 
 all: lda infer mpi_lda

```

**Comment by ghuls** [comment]
Proper fix in: https://github.com/openbigdatagroup/plda/pull/24
